spring.application.name=hotel
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# JWT Configuration (production)
#jwt.secret=SIVtq3+6k+JVE0msrImmOGkxqFnG3xqsB8RT5gx3NoqNAueD/2GvN8hxQkgD2EJ+xvrzKBzQZn5YuzW15igDhQ==
#jwt.expiration=300000

# JWT configuration for test
hotel.jwt.secret=SIVtq3+6k+JVE0msrImmOGkxqFnG3xqsB8RT5gx3NoqNAueD/2GvN8hxQkgD2EJ+xvrzKBzQZn5YuzW15igDhQ==
hotel.jwt.expiration=6000000
hotel.jwt.refreshToken=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gillkaijame@gmail.com
spring.mail.password=ptksepmbvkqqsltq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

hotel.frontEnd.host=https://lehoangninFEHost
hotel.frontEnd.forgotPasswordPath=forgotPassword
hotel.frontEnd.activeAccount=activeAccount